server:
  port: 8081

spring:
  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:stmTest-kafka}
    username: ${USERNAME:test}
    password: ${PASSWORD:qwerty1234}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: tickets