server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:/db/changelog.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:stmTest}
    username: ${USERNAME:test}
    password: ${PASSWORD:qwerty1234}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    topic: tickets

logging:
  level:
    org:
      springframework: warn
mybatis:
  type-handlers-package: org.example.mapping.handlers

pagination: 5
  
jwt:
  secret:
    access: ${JWT_ACCESS:MGJzYm52aGxpMjg5d2s1M3U5OTY5NjViaGNnMjh5ZzEwZGp4ZDZlcXIweGJhcWNueHFkMHM1cWRyaGtyaGNkNGZtemliM3lzZWQzMzdtcjh5cHFxcmlnYzZ5YW4wa2NmMWIwaXBkeHE0anlveGNxdDhvdmY1eXB6czNicHU1MjA==}
    refresh: ${JWT_REFRESH:YcIt6qiN7pmCWYKMc4fw2+AOryx12XJEhaxWwQGpRqxzt3tq6ld8pPCjqPlIINEmJDadKfne+k4v+Q1PJqDKnDrc7noBxtm1aT1LD4C9SYYYs4Ar/oLqDl4WhlSU4rl4TVk3Ul87MUPazkCcwMolXaMxVYQC8vnKOmZEYfEAfMg=}